### ISSUE TITLE
Use single websocket to connect to backend, support interleaved messages

### ISSUE THREAD

**Issue by ddengster** [osrf/rmf-web#102]
see discussion on https://github.com/osrf/romi-dashboard/pull/80#discussion_r484626426

**Comment by koonpeng** [comment]
I think this would require some changes in the server as well, I can't think of a way to support interleaved messages without a unique request id tagged to each request.

**Comment by ddengster** [comment]
I last used the JSON-RPC protocol for comms with backend servers and frontend. Recommend doing something like this.

https://en.wikipedia.org/wiki/JSON-RPC

The other question is how to handle it on the frontend side.

**Comment by koonpeng** [comment]
related to #109

**Comment by koonpeng** [comment]
Closing this, the trajectory server needs to support this before we can do anything on the client side.
