### ISSUE TITLE
Sandbox the tutorial

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf-web#125]
From Matias:
We can use the office as a tutorial, then we make sure that the actors are where we want them and well placed on the map. This would mean having the map saved in the RomiDashboard project (which it currently is, but we need to make it prettier). We could have as a new level called tutorial or have a completely different board with this tutorial.

From KP:
_A tutorial customized to the map would be great if we can get it working stably. Most games have tutorials that are sandboxed, maybe because there is too much variables going on to make a live tutorial impractical. In our case some of the scenarios we must think of is what if the map has no doors/lifts/dispensers, there is only 1 level, the map has robots but all of them are in another level, there is no trajectories or conflicts going on, the robot/door/lifts etc states changing. among many others_

Well, I think a new level for the tutorial wouldn't be the best idea but a different sandboxed board with the tutorial should do the work. We should make it easy for the end-user to return to the home page (or the main dashboard) after they finish or during the tutorial if they want to.

**Comment by koonpeng** [comment]
By the "tutorial", I guess you mean the dashboard tour? In any case, if we want to sandbox it, it should be in another page/project so it is out of the scope of the current "dashboard" package. The functionality is also going to change with the new TNG proposal so I'm closing this now. Feel free to open a discussion if you have ideas on how we should build the new tutorial.
