### ISSUE TITLE
Refactor dashboard to a reducer structure.

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf-web#143]
The dashboard file is growing more and more and as well as its number of states, it is making sense to start handling these states with reducers.

https://reactjs.org/docs/hooks-reference.html#usereducer
https://kentcdodds.com/blog/the-state-reducer-pattern-with-react-hooks

**Comment by koonpeng** [comment]
you might want to base this off of `refactor/component-lib` branch
