### ISSUE TITLE
Dispensers Panel: Dispensers with unknown state are not shown

### ISSUE THREAD

**Issue by koonpeng** [osrf/rmf-web#165]
The dispenser panel props only takes in a `DispenserState`, this causes dispenser with no state to not be shown. This results in an inconsistency as some of the dispenser icons in the map may not be in the panel.

**Comment by ChawinTan** [comment]
Right now, there is a difference between dispenserResourceManager and the stateManager. Is there any intentionto fix it from the backend side, where dispensers with an unknown state will simply be represented with an empty object instead of not being returned from the stateManager?

**Comment by koonpeng** [comment]
The problem is that there is no backend, we are receiving the state directly from the dispensers, and if the dispensers are not sending states then we simply don't know of their existence. The states also does not give us enough information to render the dispenser.

Which is why there is the `dispenserResouceManager` hack where the list of dispensers and their location are recorded in a json file, ideally rmf should provide a way to query the list of dispensers but afaik there is no such functionality.

**Comment by ChawinTan** [comment]
merged
