### ISSUE TITLE
React-component to represent states of components that are unknown

### ISSUE THREAD

**Issue by ChawinTan** [osrf/rmf-web#183]
Right now, components with unknown states are represented with a simple message in a Typography. Ideally we would want a re-usable component that can be used across the accordions of all components with more bling to it :sparkles:, or we could also notify operators in other ways, eg: (sms, an ivr?)

Feel free to give suggestions!

Related comment:
https://github.com/osrf/rmf-web/pull/169#discussion_r538964840

Related PRs:
#169 
#179

**Comment by koonpeng** [comment]
Avoid posting asana links here as that is private.

**Comment by ChawinTan** [comment]
Updated
