### ISSUE TITLE
jest/jsdom vs jasmine/karma

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf-web#185]
What do you guys think of eventually dropping jest/jsdom and move to browser based testing with karma/jasmine? That would allow us to do screenshot based snapshot testing and solves all the problem with missing web apis in jsdom. This might be more important if we want to move to a canvas based (possibly with webGL) map renderer

>The downside I'm seeing right now is that we wouldn't be able to test the Reducer change of states, I mean we will but we will do it through the browser (as a black box).

karma/jasmine tests are not black boxes. I had some confusion about karma and wdio/selenium before but afaik, the difference is that wdio tests orchestrates the browser from "outside" while karma runs the tests "inside" the browser. jasmine itself is ran inside the browser so we can still use spies to test reducers.

We definitely need some experiments to see if it's possible to migrate our tests to karma though.

>There are also some packages that use Jest to test WebGL-canvas. I think we should give it a try to make the best choice (but it's pretty sure that we are going to find missing web apis in jsdom problems).

That is the reason why I don't like jest, we must rely on these mocks which might not behave as they do on real browsers. There are also many apis not being mocked by default and we must rely on third party packages which are not maintained and might not even work anymore (last published version is 1 year ago).

>It seems to be rendering just the LMap and not the child components. So I can't access nor find the lifts

That is one of the problem with jest, leaflet uses dom apis not supported by jsdom so it's behaviour is unknown. There are also several places which we can't test with jsdom, computed svg properties for example.

_Originally posted by @koonpeng in https://github.com/osrf/rmf-web/issues/181#issuecomment-742911018_

**Comment by matiasbavera** [comment]
Hey @koonpeng what do you think about using this? https://enzymejs.github.io/enzyme/docs/guides/karma.html

I think it'll be the best of both worlds (?) We will still have a react testing library and we will use Karma to do web-based testing.

**Comment by matiasbavera** [comment]
I did some research, and apparently, we should move to Webpack to be more dynamic with our configurations and use jasmine + karma + Enzyme.

**Comment by matiasbavera** [comment]
I went into a black hole trying to get this to work. I'm still in the process.

**Comment by koonpeng** [comment]
I thought we are moving away from enzyme. I don't think we need webpack, the components are meant to be used by a react app, which will be running webpack. I don't mind using it if it makes karma easier though, but keep in mind that when we import these components on the dashboard we should be importing the js or ts files and not the webpack bundle.

**Comment by matiasbavera** [comment]
> I thought we are moving away from enzyme
Yeah, that was the initial idea, to replace Enzyme with RTL, but RTL depends on Jsdom to work. https://testing-library.com/docs/react-testing-library/setup/#using-without-jest. Maybe I'm missing something, but we have a couple of options here:
1) Keep RTL and jest to run some kind of test. In a separate folder, we can have tests that we will like to run with karma on a real dom. The good thing about this is that if Jsdom improves their API in the future we can move back to Jsdom. The bad thing is that we will be handling two ways of doing test. 
2) Keep Enzyme and move all the tests from jsdom to a browser-based test with jasmine-karma. We will be making test just in one way.
3) Use just jasmine-karma to make the assertion and test the dom with vanilla js (I think it'll be the worst-case scenario). 
4) Keep RTL and jsdom, and use selenium (the one that we use on the 2e2 tests) to test the components that are difficult for us to test with jsdom. Maybe we can do unit testing with selenium, not serving the whole application but a browser with the component we want to test (like a kind of Storybook). The good thing about this is that if Jsdom improves their API in the future we can move back to Jsdom. The bad thing is that we will be handling two ways of doing unit tests. 

> I don't think we need webpack, the components are meant to be used by a react app, which will be running webpack. I don't mind using it if it makes karma easier though, but keep in mind that when we import these components on the dashboard we should be importing the js or ts files and not the webpack bundle.

Ok, I'll give it a try.

**Comment by koonpeng** [comment]
May I'm missing something here, it says RTL should work out of the box? https://testing-library.com/docs/react-testing-library/setup/#using-without-jest
>If you're running your tests in the browser bundled with webpack (or similar) then React Testing Library should work out of the box for you.

**Comment by matiasbavera** [comment]
First of all thanks for the feedback.

> May I'm missing something here, it says RTL should work out of the box? https://testing-library.com/docs/react-testing-library/setup/#using-without-jest
> 

Yeah, it was on me I got wrong some configurations. But I got them right now. React testing library it's working with Karma. 
I think these could be alternatives on how to proceed:
### Alternative A:
 1) Move from Enzyme to RTL.
 2) Once 1) it's done implement browser-based testing Karma.

### Alternative B (have both configs and move them gradually):
 1) Create a `tests` folder on the `src` folder level (like the one we have on react-components project). Move there all the tests already converted to RTL.
2) Implement browser-based testing Karma only for that mentioned `tests` folder.
3) Move all tests from Enzyme to RTL and move them to `tests` folder. 
4) Remove Enzyme from dependencies.


Also, `RTL` offers `Mocha` as an alternative to `Jest` and `Karma`. Mocha supposed to run tests on Jsdom and browser-based depending on how it's configured, but we should use `Chai` (instead of `Jasmine`) as our assertion library. 

https://stackshare.io/stackups/karma-runner-vs-mocha

But I think if we are going to keep the web-based tests only we should keep `Karma`.

Let me know what you think

**Comment by matiasbavera** [comment]
Mmm.. I'm trying to set up Karma on the romi-dashboard and I'm having problems with external libraries (Material-ui). I'm seeing that in Angular people use dependency injection in each test to solve that problem. But I'll read more about it.

**Comment by koonpeng** [comment]
I think we start experimenting with karma only on the `react-components` package first. If that works then we can look at migrating `dashboard` tests, although that might not be needed if we can structure the tests in such a way that it avoids hitting the non-jsdom apis.

**Comment by koonpeng** [comment]
I believe this is resolved by #219
