### ISSUE TITLE
There is a dependency problem when running the bootstraper

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf-web#232]
![image](https://user-images.githubusercontent.com/11761240/109063151-9a0c5100-76c7-11eb-9db1-e987d60f7bb2.png)

**Comment by matiasbavera** [comment]
It looks that it's an issue with the last version of npm. https://stackoverflow.com/questions/64529958/error-when-trying-to-install-react-redux-dependency

It's solved by running `npm install --legacy-peer-deps`

**Comment by koonpeng** [comment]
It seems like it is not checking the dependencies of the root package, adding react-dom may fix it but it could end up installing multiple copies.

If we want to support npm 7, we may need to use workspaces, but then we can't support npm 6 if we do that.

**Comment by matiasbavera** [comment]
> If we want to support npm 7, we may need to use workspaces, but then we can't support npm 6 if we do that.

Mmm.. you're right. I think we could stay with 6 for a bit longer, but adding that to the README.. What do you think?

**Comment by koonpeng** [comment]
go ahead and make a PR :+1:
