### ISSUE TITLE
Show the exact point of conflict instead of making the world path red

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf-web#44]
## Pre- requisite
Have the websocket server use an API to determine the time of conflict and communicate this to the front end. With the time of conflict, you should be able to determine the position of conflict for each of the conflicting trajectories

## Discussion
Two trajectories from participants A & B  are in conflict if A's [`Profile::footprint`](https://github.com/osrf/rmf_core/blob/master/rmf_traffic/include/rmf_traffic/Profile.hpp) when swept along A's trajectory overlaps with B's vicinity swept along B's trajectory or vice versa. This can be checked using this [API](https://github.com/osrf/rmf_core/blob/0f155e9efea5e82d0da6723c45ee54964eb3cef5/rmf_traffic/include/rmf_traffic/DetectConflict.hpp#L54)
Checking for matching pair of (x,y) segments between two trajectories is not a good approach
* Trajectories are represented as a collection of cubic splines which are interpolated between these segment knots. Hence, two trajectories can intersect in between these segment knots. 
* While a set of segments may overlap in position, they may not do so in the time domain which can lead to incorrect conflict assumption with the above approach.

Afik the time of conflict is not reported in any of the messages published by the `rmf_traffic_schedule`. 

As a solution, we have have the websocket server use the above mentioned API to determine the time of conflict and communicate this to the front end. With the time of conflict, you should be able to determine the position of conflict for each of the conflicting trajectories. Let me know what you think.

_Originally posted by @Yadunund in https://github.com/osrf/romi-dashboard/pull/40#issuecomment-649438833_

**Comment by koonpeng** [comment]
iirc, this requires support in the trajectory server and there is nothing we can do for now. There hasn't been any updates for a long time so I'm closing this now.
