### ISSUE TITLE
Implement Localization or Internationalization in Romi dashboard

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf-web#73]
Internationalization or Localization is important for a multinational company that has a website, which would be reachable to different languages understanding people.

**Comment by matiasbavera** [comment]
This task came up from this discussion. https://github.com/osrf/romi-dashboard/pull/47#discussion_r464950712

**Comment by koonpeng** [comment]
Closing this, let's avoid over engineering things, we will look into this again when there is actual requirements for internationalization.
